server:
  port: 7001

spring:
  application:
    name: EurekaServer

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7002/eureka

