server:
  port: 8002

spring:
  application:
    name: EurekaProvider


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'