server:
  port: 7002

spring:
  application:
    name: EurekaServer
  security:
    user:
      name: zhangsan
      password: 123456
  boot:
    admin:
      client:
        url: http://localhost:8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://zhangsan:123456@localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka
  server:
    enable-self-preservation: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

